name: AVD CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-fabric:
    runs-on: ubuntu-latest
    container: ghcr.io/dlobato/netops/avd:5.7.0-python3.13-trixie-slim-e5716cc
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build fabric
        run: ansible-playbook build.yml -i inventory.yml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: fabric-intended
          path: intended
